preload = /home/denis/.config/hypr/wallpapers/dark_mountains.jpg

wallpaper {
    monitor = HDMI-A-1
    path = /home/denis/.config/hypr/wallpapers/dark_mountains.jpg
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = /home/denis/.config/hypr/wallpapers/dark_mountains.jpg
    fit_mode = cover
}

splash = false
ipc = on
