preload = /home/denis/.config/hypr/wallpapers/w1.jpg

wallpaper {
    monitor = HDMI-A-1
    path = /home/denis/.config/hypr/wallpapers/w1.jpg
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = /home/denis/.config/hypr/wallpapers/w1.jpg
    fit_mode = cover
}

splash = false
ipc = on
